name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Catalog Service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./catalog-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify -DskipTests

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          LOCAL_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalog-service:latest
          REMOTE_IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalog-service:latest

          echo "Building image: $LOCAL_IMAGE"
          ./mvnw spring-boot:build-image \
            -DskipTests \
            -Dspring-boot.build-image.imageName=$LOCAL_IMAGE

          echo "Tagging image for docker.io"
          docker tag $LOCAL_IMAGE $REMOTE_IMAGE

          echo "Pushing image: $REMOTE_IMAGE"
          docker push $REMOTE_IMAGE
